- .github/workflows/ci.yaml
> ci: publish on tag

- .github/workflows/renovate_approve.yaml
- renovate.json
> ci: update renovate config

- .github/.jira_sync_config.yaml
> Add gh jira sync

- .github/.jira_sync_config.yaml
> Fix typo (again)

- Makefile
- cmd/main.go
- deployments/helm/oathkeeper/values.yaml
- deployments/kubectl/configMap.yaml
- internal/config/specs.go
- pkg/rules/service.go
- pkg/rules/service_test.go
IAM-607
- Make the oathekeeper rules file name configurable
- Remove kubectl apply from `make dev`
> Fix make dev

- internal/openfga/client.go
- internal/openfga/client_test.go
- internal/openfga/config.go
- internal/openfga/interfaces.go
- internal/openfga/noop.go
- internal/openfga/types.go
IAM-655: openfga store layer, groundwork for the roles API
- feat: introduce BatchCheck, WriteTuples, DeleteTuples and ReadTuples in openfga client
- fix: update noop openfga client with newer methods
- feat: use interface instead of client pointer
> IAM-655 - openfga store layer

- rebac-admin-backend/v1/identities.go
- rebac-admin-backend/v1/identities_test.go
- rebac-admin-backend/v1/interfaces/identities.go
- rebac-admin-backend/v1/resources/generated_server.go
- rebac-admin-backend/v1/resources/generated_types.go
Implemented the three missing endpoints (and relative tests) from #200 .
- Implemented endpoints:
- `PATCH /identities/{id}/entitlements`
- `PATCH /identities/{id}/groups`
- `PATCH /identities/{id}/roles`
- relative unit tests
- added unit tests for `ValidationError`s
- updated generated code from latest spec
- adjusted existing code to latest generated code
- refactored http status code to leverage `http` package
> IAM-683 feat: add `PATCH /identities/{identityID}/{entitlements,groups,roles}`

- rebac-admin-backend/v1/core_test.go
- rebac-admin-backend/v1/error.go
- rebac-admin-backend/v1/swagger.go
- rebac-admin-backend/v1/swagger_test.go
This PR adds the `/swagger.json` handler.
Fixes CSS-7326
> feat: add `/swagger.json` handler

- cmd/create.go
- cmd/createFgaModel.go
- cmd/remove.go
- cmd/serve.go
- cmd/version.go
- internal/monitoring/middlewares.go
- internal/monitoring/prometheus/prometheus.go
- internal/openfga/client.go
- internal/openfga/client_test.go
- internal/openfga/noop.go
- internal/tracing/middleware.go
- internal/tracing/tracer.go
- pkg/clients/handlers.go
- pkg/clients/handlers_test.go
- pkg/clients/service.go
- pkg/clients/service_test.go
- pkg/identities/handlers.go
- pkg/identities/handlers_test.go
- pkg/identities/service.go
- pkg/idp/handlers.go
- pkg/idp/handlers_test.go
- pkg/idp/service.go
- pkg/metrics/handlers.go
- pkg/rules/handlers_test.go
- pkg/rules/service.go
- pkg/schemas/handlers.go
- pkg/schemas/handlers_test.go
- pkg/schemas/service.go
- pkg/status/handlers.go
- pkg/web/router.go
used goimports -w -local "github.com/canonical/identity-platform-admin-ui" .
> lint: sorting imports

- .github/workflows/ci-rebac-admin-backend.yaml
Unfortunately some trial and error is necessary to fix issue that happen "on merge".
> fix: CI for rebac library after weird behavior on merge

- rebac-admin-backend/v1/authentication.go
- rebac-admin-backend/v1/authentication_test.go
- rebac-admin-backend/v1/core.go
- rebac-admin-backend/v1/core_test.go
- rebac-admin-backend/v1/error.go
- rebac-admin-backend/v1/handler.go
- rebac-admin-backend/v1/identities_test.go
- rebac-admin-backend/v1/identities_validation_test.go
- rebac-admin-backend/v1/identity_providers_test.go
- rebac-admin-backend/v1/identity_providers_validation_test.go
- rebac-admin-backend/v1/interfaces/authentication.go
- rebac-admin-backend/v1/interfaces/capabilities.go
- rebac-admin-backend/v1/interfaces/entitlements.go
- rebac-admin-backend/v1/interfaces/groups.go
- rebac-admin-backend/v1/interfaces/identities.go
- rebac-admin-backend/v1/interfaces/identity_providers.go
- rebac-admin-backend/v1/interfaces/resources.go
- rebac-admin-backend/v1/interfaces/roles.go
- rebac-admin-backend/v1/response_test.go
- rebac-admin-backend/v1/roles_test.go
- rebac-admin-backend/v1/roles_validation_test.go
This PR adds the mechanisms (abstraction, middleware, and helper methods) for authentication.
Fixes CSS-7677
> feat: add abstract authentication support

- ui/package.json
> Change to AGPLv3

- pkg/clients/handlers.go
- pkg/groups/handlers.go
- pkg/identities/handlers.go
- pkg/roles/handlers.go
- pkg/rules/handlers.go
> IAM-769: add id validation to make sure it's never empty

- ui/package.json
- ui/src/App.tsx
- ui/src/components/Login.tsx
- ui/src/components/Navigation.tsx
- ui/src/components/Panels.tsx
- ui/src/index.tsx
- ui/src/sass/_login.scss
- ui/src/sass/_navigation.scss
- ui/src/sass/styles.scss
- ui/src/types/auth-user.d.ts
- ui/src/util/useLocalStorage.ts
- ui/yarn.lock
- Add a login screen and pass the auth token to the ReBACAdmin component.
- Upgrade to latest ReBAC admin.
- Enter the username for a privileged user at the login screen.
- Go to roles or groups and add a role/group.
- Check that the newly created role/group is visible in the table.
- https://warthogs.atlassian.net/browse/WD-10534
- https://warthogs.atlassian.net/browse/WD-10209
> feat: add login screen

- DEVSETUP.md
This PR adds instructions to ease team members rampup on Admin UI, in order to have a functioning deployment and to ease debug of local code without re-deploying everything everywhere all at once.
Thanks to @shipperizer for providing all the info and helping with troubleshooting.
> doc(devsetup): add instructions for dev setup for Admin UI

- .golangci.yaml
- .markdownlint.yaml
- .markdownlintignore
- .pre-commit-config.yaml
- API.md
- CONTRIBUTING.md
- DEVSETUP.md
- README.md
- renovate.json
- ui/README.md
This pull request tries to:
- Add pre-commit hooks
- Use Renovate to upgrade pre-commit hooks
- Format documentation to follow lint rules
> ci: add pre-commit hooks

- internal/authorization/types.go
- pkg/groups/handlers.go
- pkg/groups/service.go
- pkg/roles/handlers.go
- pkg/roles/service.go
IAM-725:
- Rename `Urn` to `URN`
Closes #216
> Rename Urn to URN

- README.md
- cmd/serve.go
- internal/config/specs.go
- pkg/ui/handlers.go
- pkg/web/router.go
- ui/Makefile
- Starts serving the ui pages under the `/ui` path
- The ui uses relative paths to fetch its assets
> Add UI serving

- OAUTH2.md
This PR is to provide more detail on the OAuth2 integration for the Admin Service.
This PR only adds a md file with details about what is expected of the OAuth2 client that the Admin Service is going to use to log in users.
> doc: add details for the OAuth2 integration

- .github/workflows/publish.yaml
Instal rockcraft snap to get skopeo. Tested it at https://github.com/canonical/identity-platform-admin-ui/actions/runs/9545712216
Fixes https://github.com/canonical/identity-platform-admin-ui/actions/runs/9543742812/job/26302034428
> Fix publish job

- internal/authorization/middlewares.go
> Unauthenticated handlers were called twice

- internal/validation/registry_test.go
- internal/validation/types.go
- pkg/clients/handlers.go
- pkg/clients/validation.go
- pkg/groups/handlers.go
- pkg/groups/validation.go
- pkg/identities/handlers.go
- pkg/identities/validation.go
- pkg/idp/handlers.go
- pkg/idp/validation.go
- pkg/roles/handlers.go
- pkg/roles/validation.go
- pkg/rules/handlers.go
- pkg/rules/validation.go
- pkg/schemas/handlers.go
- pkg/schemas/validation.go
IAM-931
Refactor the validation error response messages
> Improve validation error messages

- pkg/roles/service.go
> Add helper function for constructing assignee

- internal/http/types/generic.go
- pkg/clients/service_test.go
- pkg/identities/service_test.go
- pkg/rules/handlers_test.go
- pkg/schemas/service_test.go
> Remove page param

- internal/authorization/converters.go
- internal/authorization/converters_test.go
- internal/authorization/middlewares.go
- internal/authorization/middlewares_test.go
- pkg/groups/service.go
- pkg/groups/service_test.go
- pkg/roles/service.go
- pkg/roles/service_test.go
IAM-939
I have tried using the UI with this and it works, but I am not sure how to actually test that these changes are working properly.
> Use contextual tuples for admin role

- ui/src/api/auth.test.ts
- ui/src/api/auth.ts
- ui/src/api/axios.ts
- ui/src/api/client.tsx
- ui/src/api/identities.tsx
- ui/src/api/provider.tsx
- ui/src/api/schema.tsx
- ui/src/components/Layout/Layout.test.tsx
- ui/src/index.tsx
Added a custom Axios instance. This will be passed to the ReBACAdmin client so that any unauthenticated requests can be caught and then display the login screen.
https://warthogs.atlassian.net/browse/WD-14004
> WD-14004 - feat: add custom axios instance

- ui/src/api/auth.ts
- ui/src/components/Navigation.tsx
- Add link to logout with OIDC.
- Log in.
- Click the Logout link at the bottom of the side nav.
- You should get redirected back from the logout URL to the UI and you should see the login button.
https://warthogs.atlassian.net/browse/WD-13639
> WD-13639 - feat: log out with OIDC

- ui/package.json
- ui/yarn.lock
- Fixes: https://github.com/canonical/identity-platform-admin-ui/issues/373
- https://warthogs.atlassian.net/browse/WD-14064
> fix: fix wrong title displayed once logged in

- ui/src/api/client.tsx
- ui/src/api/identities.tsx
> Use correct method to invoke backend

- pkg/idp/service.go
- pkg/idp/service_test.go
- pkg/idp/third_party.go
- pkg/idp/validation.go
IAM-972: IdentityProvider v1 API
> feat: introduce IdentityProviders v1 api

- skaffold.yaml
This fixes the skaffold dev environment to allow local runs of the app.
> fix: local dev env for OIDC provider discovery

- pkg/authentication/middlewares.go
- pkg/web/router.go
Fix app when authentication is disabled
[IAM-1106](https://warthogs.atlassian.net/browse/IAM-1106)
[IAM-1106]: https://warthogs.atlassian.net/browse/IAM-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IAM-1106 fix app when authentication is disabled

- rockcraft.yaml
closes https://github.com/canonical/oci-factory/issues/259
> chore: add deb security part for oci-factory listing

- ui/src/util/basePaths.spec.ts
- ui/src/util/basePaths.ts
This PR adds the missing context path to API URLs used by the frontend to invoke Admin Service backend.
Units tests are adjusted to reflect this change.
> fix: api base path

- ui/index.html
- ui/package.json
- ui/src/App.tsx
- ui/src/components/Navigation.tsx
- ui/src/sass/styles.scss
- ui/src/urls.ts
- ui/vite.config.ts
- ui/yarn.lock
- Replace rebac admin package with admin-ui specific package (the main package will contain the v1 API ReBAC Admin client).
- Fix template for local development.
https://warthogs.atlassian.net/browse/WD-16023
> refactor: use rebac admin package for admin-ui

- .github/workflows/publish.yaml
> ci: address changes to fix canonical/oci-factory#277

- .github/workflows/publish.yaml
- SECURITY.md
- rockcraft.yaml
fixing CVE on main and added description on how to address future ones 
closing #448 and #449
> fix: adding CVE patch and patching instructions

- deployments/helm/openfga/values.yaml
Fix based on https://github.com/openfga/helm-charts/issues/161
> Fix skaffold setup

- ui/src/components/CheckboxList/CheckboxList.test.tsx
- ui/src/components/Loader/Loader.test.tsx
- ui/src/components/Logo/Logo.test.tsx
- ui/src/components/NoMatch/NoMatch.test.tsx
- ui/src/components/NoMatch/NoMatch.tsx
- ui/src/components/NoMatch/types.ts
Add tests for simple components: NoMatch, CheckboxList, Loader and Logo.
https://warthogs.atlassian.net/browse/WD-17051
https://warthogs.atlassian.net/browse/WD-17047
https://warthogs.atlassian.net/browse/WD-17048
https://warthogs.atlassian.net/browse/WD-17049
> 17049 - chore(tests): add simple component tests

- ui/src/components/Navigation/Navigation.test.tsx
- ui/src/components/Navigation/Navigation.tsx
- ui/src/components/Navigation/types.ts
Add tests for the Navigation component.
https://warthogs.atlassian.net/browse/WD-17050
> WD-17050 - chore(tests): add Navigation component tests

- ui/src/components/Loader/Loader.tsx
- ui/src/components/Loader/index.ts
- ui/src/components/Loader/test-types.ts
- ui/src/components/SidePanel/SidePanel.test.tsx
- ui/src/components/SidePanel/SidePanel.tsx
- ui/src/components/SidePanel/types.ts
- ui/src/test/utils.tsx
Add test to the SidePanel and subcomponents
https://warthogs.atlassian.net/browse/WD-17055
> WD-17055 - chore(tests): add SidePanel tests

- pkg/authentication/handlers_test.go
- pkg/authentication/oidc.go
- pkg/authentication/oidc_test.go
IAM-1225
This reverts commit 4bad945bc8dfe50b9d75f4e129115a23938bc6d4.
> Revert commit

- ui/src/components/DeletePanelButton/DeletePanelButton.test.tsx
- ui/src/components/DeletePanelButton/DeletePanelButton.tsx
- ui/src/components/DeletePanelButton/index.ts
- ui/src/components/DeletePanelButton/types.ts
- ui/src/pages/clients/DeleteClientBtn/DeleteClientBtn.test.tsx
- ui/src/pages/clients/DeleteClientBtn/DeleteClientBtn.tsx
- ui/src/pages/clients/DeleteClientBtn/types.ts
- ui/src/pages/identities/DeleteIdentityBtn/DeleteIdentityBtn.test.tsx
- ui/src/pages/identities/DeleteIdentityBtn/DeleteIdentityBtn.tsx
- ui/src/pages/identities/DeleteIdentityBtn/types.ts
- ui/src/pages/providers/DeleteProviderBtn/DeleteProviderBtn.test.tsx
- ui/src/pages/providers/DeleteProviderBtn/DeleteProviderBtn.tsx
- ui/src/pages/providers/DeleteProviderBtn/types.ts
Create shared delete button component.
Add tests to delete buttons.
https://warthogs.atlassian.net/browse/WD-17060
https://warthogs.atlassian.net/browse/WD-17062
https://warthogs.atlassian.net/browse/WD-17066
> WD-17060 - chore(tests): add delete button tests

- go.mod
- go.sum
- pkg/schemas/gRPC_handlers.go
- pkg/schemas/gRPC_handlers_test.go
- pkg/schemas/gRPC_mappers.go
- pkg/schemas/gRPC_mappers_test.go
- pkg/web/router.go
This pull request aims to migrate the schemas API.
> feat: porting schemas API

- go.mod
- go.sum
- pkg/clients/gRPC_handlers.go
- pkg/clients/gRPC_handlers_test.go
- pkg/clients/gRPC_mappers.go
- pkg/clients/gRPC_mappers_test.go
- pkg/web/router.go
This pull request tries to migrate the clients API.
> feat: porting clients API

- go.mod
- go.sum
- pkg/clients/gRPC_handlers.go
- pkg/clients/gRPC_handlers_test.go
- pkg/identities/gRPC_handlers.go
- pkg/identities/gRPC_handlers_test.go
- pkg/schemas/gRPC_handlers.go
- pkg/schemas/gRPC_handlers_test.go
This pull request aims to use the updated pagination in the protobuf models.
> fix: fix the pagination field
