- Makefile
- cmd/main.go
- deployments/helm/hydra/values.yaml
- deployments/helm/oathkeeper/values.yaml
- deployments/kubectl/configMap.yaml
- go.mod
- go.sum
- internal/config/specs.go
- internal/oathkeeper/client.go
- pkg/rules/handlers.go
- pkg/rules/handlers_test.go
- pkg/rules/interfaces.go
- pkg/rules/service.go
- pkg/rules/service_test.go
- pkg/web/router.go
- skaffold.yaml
- structure-tests.yaml
This PR includes the implementation of the Admin UI Rest interface to access and manipulate Oathkeeper access rules.
Testing Guide:
The following endpoints have been implemented for Admin UI:
Get /api/v0/rules
Get /api/v0/rules/{id}
Post /api/v0/rules
Put /api/v0/rules
Delete /api/v0/rules/{id}
{id} is a URL parameter that accepts the Oathkeeper rule IDs specified in a Kubernetes configmap.
The make command make dev sets up a development environment.
> IAM-337-Implement Oathkeeper integration

- Makefile
- build.sh
- deployments/kubectl/configMap.yaml
- deployments/kubectl/deployment.yaml
- deployments/kubectl/job.yaml
- deployments/kubectl/storage.yaml
- skaffold.yaml
This pull request tries to solve the issue in the provisioning development setup. The admin service needs the openFGA store ID and model ID to be passed in.
The proposed setup uses a k8s job, instead of using init containers in Admin UI deployment, to create openFGA store and model and share them with the admin service by using persistent volume. This is specifically to avoid potential race conditions that could be caused by multiple Admin UI replicas.
> feat: passing openfga store and model id to admin service

- go.mod
- go.sum
- rebac-admin-backend/v1/core.go
- rebac-admin-backend/v1/core_test.go
- rebac-admin-backend/v1/groups.go
- rebac-admin-backend/v1/service.go
This PR adds the main types of the library (e.g., params, constructor, some abstractions) and also creates HTTP handlers. A few tests are added to verify it works fine with both Golang standard HTTP multiplexer and Chi Mux.
This PR is based on the other branch (pushed in #194). That's why you see a lot of changes, but once the other PR lands, this one will shrink.
Fixes CSS-7249
> (ReBAC library) Add main types

- internal/authorization/converters.go
- internal/authorization/converters_test.go
- internal/authorization/middlewares.go
- internal/authorization/middlewares_test.go
IAM-655: first iteration on the authorization middleware
code relies on the model defined in the spec [ID-034](https://docs.google.com/document/d/1GMoTB6MtfUtfv_gUTjrWZWqv2dH7jVhJQCS4gLKoD7o/edit?usp=sharing)
to be plugged as middleware, please use the `With` directive, not `Use` due to how the[ `URLParam` function operates](https://stackoverflow.com/a/70516491)
```
middlewares := make(chi.Middlewares, 0)
middlewares = append(
middlewares,
middleware.RequestID,
middleware.RequestLogger(logging.NewLogFormatter(logger)), // LogFormatter will only work if logger is set to DEBUG level,
)
router.Use(middlewares...)
chiMux := router.With(authMdw).(*chi.Mux)
roles.NewAPI(roles.NewService(ofga, tracer, monitor, logger), tracer, monitor, logger).RegisterEndpoints(chiMux)
``` 
- feat: authorization …
> IAM-655 - authz/middleware

- rebac-admin-backend/v1/core.go
- rebac-admin-backend/v1/error.go
- rebac-admin-backend/v1/response.go
- rebac-admin-backend/v1/response_test.go
This PR applies proper error formatting to match the OpenAPI spec, by implementing a custom `ErrorHandlerFunc` function. This also introduces some generic error types (e.g., `UnauthorizedError` or `NotFoundError`) which should be used by custom backends).
Some test cases are added to verify errors added are correctly formatted to a `Response` type.
Fixes CSS-7327
> (ReBAC library) Implement proper error formatting

- rebac-admin-backend/Makefile
- rebac-admin-backend/v1/error.go
- rebac-admin-backend/v1/identities_test.go
- rebac-admin-backend/v1/response.go
- rebac-admin-backend/v1/response_test.go
This PR applies some refactoring on error types. A new internal type, named `errorWithCode` is introduced, with a few exported helper methods to let users create errors.
Fixes CSS-7530
> fix: refactor error types

- rebac-admin-backend/v1/handler.go
- rebac-admin-backend/v1/identity_providers.go
- rebac-admin-backend/v1/identity_providers_test.go
- rebac-admin-backend/v1/interfaces/identity_providers.go
- rebac-admin-backend/v1/resources/generated_server.go
- rebac-admin-backend/v1/resources/generated_types.go
Implementations on the `/authentication` endpoints handlers. This builds on top of the work done for #200 .
- updated generated code after [PR28](https://github.com/canonical/openfga-admin-openapi-spec/pull/28)
- added implementation for mentioned endpoints
- added unit tests
> feat: add `/authentication` API set handlers implementation

- rebac-admin-backend/v1/capabilities.go
- rebac-admin-backend/v1/capabilities_test.go
- rebac-admin-backend/v1/handler.go
- rebac-admin-backend/v1/interfaces/capabilities.go
Implementations on the `/capabilities` endpoints handlers. This builds on top of the work done for #200 
- added implementation for mentioned endpoints
- added unit tests
> feat: add `/capabilities` API set handler implementation

- rebac-admin-backend/v1/entitlements.go
- rebac-admin-backend/v1/entitlements_test.go
- rebac-admin-backend/v1/handler.go
- rebac-admin-backend/v1/interfaces/entitlements.go
This PR builds on top of the work done in #200 , and will need to be rebased on top of `feature-rebac-admin-ui-backend` branch after #207 gets merged: this PR real commits are only the last 3.
Implementations on the /capabilities endpoints handlers.
- added implementation for mentioned endpoints
- added unit tests
> feat: add `/entitlements` API set handler implementation

- rebac-admin-backend/Makefile
- rebac-admin-backend/v1/core.go
- rebac-admin-backend/v1/groups.go
- rebac-admin-backend/v1/groups_test.go
- rebac-admin-backend/v1/handler.go
- rebac-admin-backend/v1/identities.go
- rebac-admin-backend/v1/identities_test.go
- rebac-admin-backend/v1/interfaces/groups.go
- rebac-admin-backend/v1/interfaces/identities.go
- rebac-admin-backend/v1/roles_test.go
This PR implements handlers for `/groups` endpoints. It also fixes some minor issues with other endpoints' tests.
Fixes CSS-7255
> feat: add `/groups` endpoints

- rebac-admin-backend/v1/core.go
- rebac-admin-backend/v1/handler.go
- rebac-admin-backend/v1/interfaces/resources.go
- rebac-admin-backend/v1/resources.go
- rebac-admin-backend/v1/resources_test.go
This PR adds `/resources` endpoints.
Fixes CSS-7259
> feat: add `/resources` endpoints

- rebac-admin-backend/v1/capabilities.go
- rebac-admin-backend/v1/core.go
- rebac-admin-backend/v1/entitlements.go
- rebac-admin-backend/v1/entitlements_test.go
- rebac-admin-backend/v1/error.go
- rebac-admin-backend/v1/groups.go
- rebac-admin-backend/v1/identities.go
- rebac-admin-backend/v1/identity_providers.go
- rebac-admin-backend/v1/identity_providers_test.go
- rebac-admin-backend/v1/resources.go
- rebac-admin-backend/v1/response.go
- rebac-admin-backend/v1/response_test.go
- rebac-admin-backend/v1/roles.go
- rebac-admin-backend/v1/roles_test.go
This PR polished the way we map errors thrown by services (e.g., `IdentitiesService`) to the OpenAPI spec response type.
This PR also:
- Removes the unused `delegateErrorResponseMapper` type and applies the same approach within the `mapServiceErrorResponse` function.
- Drops unused `skip` variable from table tests.
- Fixes `handler` struct instantiation by providing it with all services. 
- Adds explicit `Content-Type: application/json` header to responses.
- Improve some field names by removing the `Service` suffix.
Fixes CSS-7635
> fix: polish writing service error responses

- rebac-admin-backend/v1/handler.go
This PR drops `resources.Unimplemented` as an embedded struct in `handler`. This based on top of #210, so this should be merged after that.
Fixes CSS-7311
> fix: remove `resources.Unimplemented` embedded struct

- rebac-admin-backend/v1/identities.go
- rebac-admin-backend/v1/identities_test.go
- rebac-admin-backend/v1/interfaces/identities.go
- rebac-admin-backend/v1/resources/types.go
- rebac-admin-backend/v1/resources/types_test.go
This PR adds the wrapper struct for paginated response, so that service backends can actually pass all the info needed to build the http response for collections data returned as pages.
This allows the library to fill the `_meta` and the `_links` fields correctly.
- add `PaginatedResponse` generic type with one public method
- add tests for it
- adopted the new type for paginated responses **on the identity endpoint only** to avoid time waste, other endpoint will follow after this PR is merged
- adjusted tests
> feat: add paginated response generic struct

- deployments/kubectl/storage.yaml
Using the static provision might cause some issues in different versions of microk8s clusters. This pull request tries to use the microk8s default StorageClass `microk8s-hostpath` enabled by the addon [`hostpath-storage`](https://microk8s.io/docs/addon-hostpath-storage).
> fix: use the microk8s-hostpath storageclass to dynamically provision the persistent volumn

- rebac-admin-backend/v1/capabilities.go
- rebac-admin-backend/v1/capabilities_test.go
- rebac-admin-backend/v1/entitlements.go
- rebac-admin-backend/v1/entitlements_test.go
- rebac-admin-backend/v1/groups.go
- rebac-admin-backend/v1/groups_test.go
- rebac-admin-backend/v1/identity_providers.go
- rebac-admin-backend/v1/identity_providers_test.go
- rebac-admin-backend/v1/interfaces/capabilities.go
- rebac-admin-backend/v1/interfaces/entitlements.go
- rebac-admin-backend/v1/interfaces/groups.go
- rebac-admin-backend/v1/interfaces/identity_providers.go
- rebac-admin-backend/v1/interfaces/resources.go
- rebac-admin-backend/v1/interfaces/roles.go
- rebac-admin-backend/v1/resources.go
- rebac-admin-backend/v1/resources_test.go
- rebac-admin-backend/v1/roles.go
- rebac-admin-backend/v1/roles_test.go
- rebac-admin-backend/v1/swagger.go
This PR follows the work done on #214 , to complete the refactoring to adopt the newly introduced `PaginatedResponse`.
This refactoring affects endpoint hanlder, interface and tests for the following endpoints:
- capabilities
- entitlements
- gruops
- identity-providers
- resources
- roles
> Complete paginated response refactoring after #214

- .github/workflows/ci-rebac-admin-backend.yaml
This PR fixes the CI action introduces in #224 to generate mocks before running the linting.
> fix: reback CI failing for missing mocks

- api.MD
IAM-721: first draft of API documentation
> docs: add bare API documentation

- internal/authorization/converters.go
- internal/authorization/converters_test.go
- internal/authorization/middlewares.go
- internal/authorization/middlewares_test.go
- pkg/groups/handlers.go
- pkg/groups/handlers_test.go
- pkg/groups/interfaces.go
- pkg/groups/service.go
- pkg/groups/service_test.go
IAM-366: groups API following openapi spec v0.8.0 (to a degree)
- **feat: handlers for groups API**
- **feat: create groups service**
- **feat: introduce groups API converter to deal with authorization in the middleware**
> IAM 366: Groups API

- internal/openfga/noop.go
NoopClient was returning an empty response and a nil error, this triggered
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x178ca01]
goroutine 77 [running]:
github.com/canonical/identity-platform-admin-ui/pkg/roles.(*Service).removePermissionsByType(0xc0008bcf00, {0x1ebc708?, 0xc0005cd800?}, {0xc0003d07f5, 0x6}, {0x1bf2a94, 0x6})
/root/parts/go-build/build/pkg/roles/service.go:292 +0x261
github.com/canonical/identity-platform-admin-ui/pkg/roles.(*Service).DeleteRole.func1({0x1bf2a94?, 0x0?})
/root/parts/go-build/build/pkg/roles/service.go:245 +0x77
created by github.com/canonical/identity-platform-admin-ui/pkg/roles.(*Service).DeleteRole in goroutine 70 …
```
> fix: address segfault when using noop client

- pkg/groups/service.go
- pkg/groups/service_test.go
IAM-773: addressing group entitlements issue, closes #243
> IAM-773: drop non can_ relations from group entitlements

- internal/http/types/token.go
- internal/http/types/token_test.go
- pkg/groups/handlers.go
- pkg/roles/handlers.go
This PR provides a new method to set multiple tokens at a time on the `TokenPaginator` object, while also adding tests for non-trivial methods.
- sorted imports and added godocs
- added `SetTokens` method
- now both `SetToken` and `SetTokens` methods don't actually set empty token values, in order to have an empty TokenHeader in case no continuation tokens are available
- added tests for non-trivial methods
#238
> feat: TokenPaginator enhancements + fix to properly handle empty tokens

- pkg/schemas/service.go
- pkg/schemas/service_test.go
IAM-783: bug with empty data field in k8s configmap
closes #254
> IAM-783: deal with empty Data attribute in k8s configmap

- ui/index.html
- ui/src/App.tsx
- ui/src/api/identities.tsx
- ui/src/api/schema.tsx
- ui/src/components/Logo.tsx
- ui/src/components/Navigation.tsx
- ui/src/pages/identities/IdentityList.tsx
- ui/src/pages/schemas/SchemaList.tsx
- ui/src/types/identity.d.ts
- ui/src/types/schema.d.ts
- change logo copy and page title to "Identity Platform"
- added read only screen for schemas
- added read only screen for identities
- added navigation entries for schemas and identities
- added typescript crud bindings for schemas and identities
> UI: Add schemas and identities read only screens WD-10036

- deployments/kubectl/configMap.yaml
IAM-749: openfga client config validation needs store and model ids set, the k8s job will
substitute those with valid values in the dev setup
> IAM-749: set openfga model and store env vars to dummy values for correct validation of admin-ui

- cmd/createFgaModel.go
- skaffold.yaml
IAM-749: drop validation of openfga config in `create-model` command
also:
- allow grace period on deployment to let k8s job to its course and change the configmap
```
shipperizer in ~/shipperizer/identity-platform-admin-ui on IAM-749 ● λ make dev
after job admin-ui-openfga-setup has run, restart the identity-platform-admin-ui deployment
to make sure the changes in the configmap are picked up
Generating tags...
- identity-platform-admin-ui -> localhost:32000/identity-platform-admin-ui:v1.5.0-104-gffd6563-dirty
Starting build...
Building [identity-platform-admin-ui]...
Target platforms: [linux/amd64]
Starting rockcraft, version 1.2.3
Logging execution to '/home/shipperizer/.local/state/rockcraft/log/rockcraft-20240403-081206.459244.log'
Launching managed ubuntu 22.04 instance...
Starting …
```
> fix: skip validation config on createFGAmodel cmd

- internal/validation/registry.go
- internal/validation/registry_test.go
- internal/validation/types.go
- pkg/clients/handlers.go
- pkg/groups/handlers.go
- pkg/identities/handlers.go
- pkg/idp/handlers.go
- pkg/roles/handlers.go
- pkg/rules/handlers.go
- pkg/schemas/handlers.go
- pkg/web/router.go
This PR introduces what's needed to have validation on each APIs, leveraging both custom `ValidationRegistry` struct (introduced by this PR) and 3rd party `validator` already part of the project dependencies.
- updated license on touched files
- introduced `ValidationRegistry` object for registering validating functions for each API
- introduced 3rd party validator in each API struct to perform the actual validation
- tests on added code
> feat: setup validation for APIs

- internal/validation/registry.go
- internal/validation/registry_test.go
- internal/validation/types.go
- pkg/clients/handlers.go
- pkg/groups/handlers.go
- pkg/groups/handlers_test.go
- pkg/groups/validation.go
- pkg/groups/validation_test.go
- pkg/identities/handlers.go
- pkg/identities/handlers_test.go
- pkg/identities/validation.go
- pkg/identities/validation_test.go
- pkg/idp/handlers.go
- pkg/roles/handlers.go
- pkg/rules/handlers.go
- pkg/schemas/handlers.go
- pkg/schemas/handlers_test.go
- pkg/schemas/service.go
- pkg/schemas/validation.go
- pkg/schemas/validation_test.go
This PR introduces the first implementation for the validation layer. Validation is delegated to each validatingFunction that handlers register through the `RegisterValidation` method. The process is run inside one middleware provided by the `ValidationRegistry` object.
Example:
```golang
groupsAPI := groups.NewAPI(/*...*/)
groupsAPI.RegisterValidation(vldtr)
```
- enahnced Validation errors with detailed errors for the UI to consume
- added tests
- api struct validators (3rd party) enhanced to let errors use the json field name to avoid discrepancy between fields used by UI and fields referenced by backend errors
- added validation constraint on URL Params for endpoints to forbid empty values
- added implementation of validation process for the following handlers
- schemas
- groups
- …
> IAM 776 Implement validation for `groups`, `schemas`, `identities` handlers

- ui/README.md
- ui/src/api/client.tsx
- ui/src/api/identities.tsx
- ui/src/api/schema.tsx
- ui/src/components/IconLeft.tsx
- ui/src/components/IconRight.tsx
- ui/src/components/Pagination.tsx
- ui/src/components/Panels.tsx
- ui/src/pages/clients/ClientList.tsx
- ui/src/pages/identities/DeleteIdentityBtn.tsx
- ui/src/pages/identities/IdentityCreate.tsx
- ui/src/pages/identities/IdentityForm.tsx
- ui/src/pages/identities/IdentityList.tsx
- ui/src/pages/providers/ProviderList.tsx
- ui/src/pages/schemas/SchemaList.tsx
- ui/src/types/api.d.ts
- ui/src/util/api.tsx
- ui/src/util/usePagination.tsx
- ui/src/util/usePanelParams.tsx
- Add pagination to clients, schemas and identity lists in ui.
- Add identity creation form
- Add identity deletion
fixes WD-10253
> UI: add pagination and identity creation

- deployments/kubectl/job.yaml
this will mean that at each `make dev` run a new store and model will be created 
assumption is that make dev is a one off command for bootstrapping the setup, not an iterative command to run
> ci: add cleanup of job after 60s

- internal/validation/registry_test.go
- pkg/clients/handlers.go
- pkg/clients/handlers_test.go
- pkg/clients/validation.go
- pkg/clients/validation_test.go
- pkg/groups/handlers.go
- pkg/groups/validation.go
- pkg/groups/validation_test.go
- pkg/identities/handlers.go
- pkg/identities/validation.go
- pkg/identities/validation_test.go
- pkg/idp/handlers.go
- pkg/idp/handlers_test.go
- pkg/idp/third_party.go
- pkg/idp/validation.go
- pkg/idp/validation_test.go
- pkg/roles/handlers.go
- pkg/roles/handlers_test.go
- pkg/roles/validation.go
- pkg/roles/validation_test.go
- pkg/rules/handlers.go
- pkg/rules/handlers_test.go
- pkg/rules/validation.go
- pkg/rules/validation_test.go
- pkg/schemas/handlers.go
- pkg/schemas/validation.go
- pkg/schemas/validation_test.go
- pkg/web/router.go
This PR implements validation for remaining APIs, and add tests for all of them.
It also improves previously added tests from #275 .
It also enables validation (basically reverting the changes from #278 ), while also renaming the variable to something more explicit.
Added comments on validation tags to be explicit about what validation is performed.
> IAM 776 Implement validation for all handlers

- internal/authorization/converters.go
- pkg/groups/service.go
- pkg/groups/service_test.go
closes #283
```
shipperizer in ~/shipperizer/identity-platform-admin-ui on IAM-847 ● λ http :8000/api/v0/groups/test/identities  X-Authorization:$PRIVILEGED_USER
HTTP/1.1 200 OK
Content-Length: 87
Content-Type: application/json
Date: Mon, 22 Apr 2024 12:33:28 GMT
X-Token-Pagination:
{
"_meta": null,
"data": [
"user:shipperizer"
],
"message": "List of identities",
"status": 200
}
shipperizer in ~/shipperizer/identity-platform-admin-ui on IAM-847 ● λ http PATCH :8000/api/v0/groups/test/identities identities:='["tom","jerry"]' X-Authorization:$PRIVILEGED_USER
HTTP/1.1 201 Created
Content-Length: 86
Content-Type: application/json
Date: Mon, 22 Apr 2024 12:33:36 GMT
{
"_meta": null,
"data": null,
"message": "Updated identities for group test",
"status": 201
}
shipperizer in …
```
> fix: removing extra #member on assignIdentities service call

- README.md
- cmd/serve.go
- internal/config/specs.go
- internal/k8s/client.go
Applied @shipperizer changes to streamline K8s client and to externalize the kubeconfig file path for development purposes.
Updated license.
> refactor: k8s client with externalized kubeconfig file path

- Makefile
- README.md
- cmd/serve.go
- internal/config/specs.go
- pkg/web/router.go
This PR adds a config key to allow developers to run the backend with control over the payload validation process (enabled/disabled). Defaults to true.
- refactor `NewRouter` func to take one holder object instead of multiple config objects
- added `payload_validation_enabled` config key to allow control over payload validation processes
- updated Readme `Environment Variables` sections
- added `--tail` flag to `skaffold` command in `make dev` in order to have skaffold tail logs
> feat: add config env var for enabling/disabling payload validation

- pkg/groups/handlers.go
- pkg/groups/service.go
- pkg/groups/service_test.go
This PR fixes unexpected behavior when invoking the group API.
Similar to the work done in #295 .
- CreateGroup now adds the explicit entitlement `can_view` to user:{userID} since it would not work otherwise
- GetGroupDetail now returns
- the group id in case it's present and the user is allowed to view it
- 404 in case the group is not present and the user is allowed to view
- 403 in case the user is not allowed to view it (no matter if the role is present or not, this info is concealed from the unauthorized user)
- DeleteRole now removes also all direct associations from the group, meaning all `can_view`, `can_edit`, `can_delete`, `can_create`, `member`, `privileged` are removed when the group is removed
- tests are adjusted
NB: a subsequent PR will take care of returning errors from …
> IAM 867 fix groups handlers

- pkg/groups/handlers.go
- pkg/groups/handlers_test.go
- pkg/groups/interfaces.go
- pkg/groups/service.go
- pkg/groups/service_test.go
- pkg/groups/validation.go
- pkg/groups/validation_test.go
- pkg/roles/handlers.go
- pkg/roles/handlers_test.go
- pkg/roles/interfaces.go
- pkg/roles/service.go
- pkg/roles/service_test.go
- pkg/roles/validation.go
- pkg/roles/validation_test.go
This PR tries to bring uniformity to Admin UI APIs in order to avoid breaking changes in the future (or at least reduce them to the least possible). This involves never letting users specify ID for resource creations, but rely on a different identifier.
Also, now invocations like `GET /groups/{id}` will return a json instead of a single string. The json response will include both the ID and the identifier provided at creation time.
This fixes #271
> IAM 834 Use `name` identifier for `Groups`, and `Roles` creation

- pkg/groups/handlers.go
- pkg/groups/handlers_test.go
- pkg/groups/interfaces.go
- pkg/groups/service.go
- pkg/groups/service_test.go
- pkg/roles/handlers.go
- pkg/roles/handlers_test.go
- pkg/roles/interfaces.go
- pkg/roles/service.go
- pkg/roles/service_test.go
With this PR creation endpoints for Roles and Groups now also return the body of the created entity as the only element of the `data` array.
Closes #302 .
> feat: return created entity in response body for `Role`s and `Group`s

- ui/package.json
- ui/yarn.lock
Upgrade to the latest rebac-admin with support for `name` attributes (https://github.com/canonical/identity-platform-admin-ui/pull/297).
https://warthogs.atlassian.net/browse/WD-10953
> WD-10953 - feat: upgrade rebac-admin to 0.0.1-alpha.3

- internal/http/types/generic.go
- pkg/rules/handlers.go
- pkg/rules/handlers_test.go
- pkg/rules/service.go
This PR adopts the page_token strategy for pagination of Rules List API, with an encoded offset.
Fixes #268
> IAM 829 Use token pagination strategy for Rules API

- OAUTH2.md
- cmd/serve.go
- internal/config/specs.go
- pkg/authentication/cookies.go
- pkg/authentication/cookies_test.go
- pkg/authentication/handlers.go
- pkg/authentication/handlers_test.go
- pkg/authentication/interfaces.go
- pkg/authentication/middlewares.go
- pkg/authentication/middlewares_test.go
- pkg/authentication/oidc.go
- pkg/web/router.go
This PR introduces the middleware functionalities to authenticate invocations via either a bearer token (access token only, no refresh) or ID and access token (with possible refresh in case one of the tokens is expired and a refresh token is available and valid).
This PR also changes the behavior of the callback endpoint which previously returned a json response with three tokens, now redirects to the content of `UIPrefix` as a URL. This needs to be fixed/improved, and I opened the issue to track this - https://github.com/canonical/identity-platform-admin-ui/issues/337.
1. if the request is against an endpoint whose prefix is allowlisted, then no checks are run, otherwise...
2. check for bearer token in the `Authorization` header (CLI use case)
2.a if available, we rely on that as an …
> IAM 892 - login handler and authentication middleware implementation according to spec ID036

- internal/authorization/admin.go
- internal/authorization/authorization.go
- internal/authorization/converters.go
- internal/authorization/converters_test.go
- internal/authorization/interfaces.go
- internal/authorization/middlewares.go
- internal/authorization/middlewares_test.go
- internal/openfga/client.go
- internal/openfga/noop.go
- pkg/groups/interfaces.go
- pkg/roles/interfaces.go
- pkg/web/interfaces.go
IAM-910
- Prefix the global object
- Use contextual tuples so that logic for global read and admin access is not persisted to openfga
One issue that we need to look into is that users will be able to create a role or a group called `__system__global` and it will collide with our tuples. One way around this is to add a check either on the roles/groups API or on the openfga module to prevent writes and deleted of objects that start with the system prefix. I can work on this on this PR or I can create an issue (I prefer the latter).
Once this PR is merged, we will no longer need to add the tuples with `<resource>:global` to openfga. I will remove them from the wiki.
I have tested it manually, but please take some time to test it yourselves as I might have missed some functionality.
Closes …
> Add contextual tuples for global read and admin access

- pkg/authentication/handlers.go
- pkg/authentication/handlers_test.go
- pkg/authentication/middlewares.go
This PR builds on top of #338 , so it will need a rebase after that one is merged.
It introduces a simple `me` handler to allow clients to retrieve info about the currently logged user.
This is useful for frontend applications which can rely on this endpoint to know who is the user that is currently logged in.
- `isAllowListed` method now relies on an exact match for it's matching strategy, leaving the previous prefix based matching behind
- `nonce` field is now ignored when serializing the `Principal` struct
> IAM 887 Add `/auth/me` endpoint to retrieve info about currently logged user

- cmd/serve.go
- internal/config/specs.go
- pkg/authentication/cookies.go
- pkg/authentication/handlers.go
- pkg/authentication/handlers_test.go
- pkg/authentication/interfaces.go
- pkg/authentication/oidc.go
- pkg/authentication/oidc_test.go
Adds the logout handler `/api/v0/auth/logout` which does two things mainly
- deletes the hydra session (in case the Principal is a browser user, otherwise no session info is availble for CLI)
- revokes the refresh token (if present, access token otherwise) so they cannot be used anymore
Of course it also deletes the encrypted auth cookies.
Hydra admin url is used for the revoke session API invocation, here we rely on hydra implementation of this so I made explicit reference to hydra url since there is no need to keep it generic. In case we ever change from Hydra to another OIDC provider, we'll have to switch the logout implementation anyway.
This PR also fixes cookie deletion for the cookie manager, since a bug was present and it slipped in the PR it introduced it.
**NB**: The revoke …
> IAM 889 Implement logout feature

- README.md
- cmd/serve.go
- internal/config/specs.go
- pkg/authentication/cookies.go
- pkg/authentication/cookies_test.go
- pkg/authentication/handlers.go
- pkg/authentication/handlers_test.go
- pkg/authentication/interfaces.go
- pkg/ui/handlers.go
- pkg/web/router.go
Two things come with this PR
- a small fix to the ui serving handlers and semplification of the implementation
- a feature which allows the frontend to pass a `next` query param with the login GET request, which allows the FE to get that value back **after** login completes so it can use/interpret it (this should be used by the FE to know where the login request originated from in order to bring the user back to that UI).
The `next` parameter does not need to be a relative url or anything similar, it's just parsed as a string and it is returned as it is.
The UI can use it in whichever way it wants.
This closes #337
> IAM 933 - Fix UI serving and implement `next` param passing for FE deep redirection

- pkg/ui/handlers.go
This PR comes after a chat with @huwshimi to allow for time to consider better solutions to handle redirects to the frontend SPA.
See #353 .
This implements the redirect from `/ui` to `/ui/` to let the assets download work.
This will be improved in the near future to make the system less fragile.
> fix: temporary fix to allow time for new solution on the frontend for UI redirect

- pkg/authentication/cookies.go
Needed for when the api is served under a subpath
> Set cookie path to /

- internal/authorization/authorization.go
- internal/authorization/interfaces.go
- internal/authorization/middlewares.go
- internal/authorization/middlewares_test.go
- internal/authorization/resource_manager.go
- internal/config/specs.go
- pkg/authentication/handlers.go
- pkg/authentication/handlers_test.go
- pkg/authentication/interfaces.go
- pkg/authentication/middlewares.go
- pkg/authentication/middlewares_test.go
- pkg/authentication/oidc.go
- pkg/authentication/oidc_test.go
- pkg/authentication/principal.go
- pkg/authentication/tokens.go
- pkg/authentication/tokens_test.go
- pkg/groups/handlers.go
- pkg/groups/handlers_test.go
- pkg/roles/handlers.go
- pkg/roles/handlers_test.go
- pkg/web/router.go
This PR links authenticated principals to the authorization model in OpenFGA.
This means that either a ServicePrincipal (CLI use case) or a UserPrincipal (browser use case) will be "mapped" to a OpenFGA user of a tuple throught the new `Identifier()` method.
For `ServicePrincipal`s (representing an OAuth2 client authenticated through `client_credentials` grant against Hydra), the subject will match the client-id of that specific OAuth2 client that generated the token. So in this case the identifier will be the value of the client-id coming form the `sub`claim.
For `UserPrincipal`s (representing a "human" user authenticated through the `authorization_code` grant against Hydra), the `email` claim will be used as the principal identifier.
This way we will be able to have OpenFGA tuples with …
> IAM-891 link authenticated users to authorization model

- cmd/serve.go
- pkg/ui/handlers.go
The current logic is bugged, `r.URL.Path` does not always contain the full path (when running behind a reverse proxy, the proxy changes the path when forwarding the requests)
> Use contextPath to redirect to UI

- ui/package.json
This removes the grep that prevents extra arguments being passed to the `yarn dev-serve command`. Specifically, we need to be able to pass the port for some dev setups: `yarn dev-serve --port 8000`. In those cases `localhost:8000` is a valid address so don't want to remove it from the output.
https://warthogs.atlassian.net/browse/WD-13665
> WD-13665 - fix: allow UI port to be set

- ui/package.json
- ui/src/api/auth.test.ts
- ui/src/api/auth.ts
- ui/src/api/client.tsx
- ui/src/api/identities.tsx
- ui/src/api/provider.tsx
- ui/src/api/schema.tsx
- ui/src/components/Layout/Layout.test.tsx
- ui/src/components/Login/Login.tsx
- ui/src/index.tsx
- ui/src/pages/clients/ClientCreate.tsx
- ui/src/pages/clients/ClientEdit.tsx
- ui/src/pages/providers/DeleteProviderBtn.tsx
- ui/src/pages/providers/ProviderList.tsx
- ui/src/test/setup.ts
- ui/src/util/api.tsx
- ui/src/util/basePaths.spec.ts
- ui/src/util/basePaths.ts
- ui/yarn.lock
- Migrate API calls to Axios.
- Set API base path using Axios config.
This change means we can centrally handle 401 errors for all API calls and display the OIDC login if needed.
https://warthogs.atlassian.net/browse/WD-13813
> WD-13813 - refactor: migrate API calls to Axios

- ui/package.json
- ui/src/App.test.tsx
- ui/src/App.tsx
- ui/yarn.lock
- Add a global error handler. https://warthogs.atlassian.net/browse/WD-13636
- Display login if 401 response is received for any API response. https://warthogs.atlassian.net/browse/WD-13637
- Log in.
- In another tab log out (visit http://localhost:8000/api/v0/auth/logout).
- Go back to the first tab and click on a different page.
- The API should return a 401 and the login button should get displayed.
> WD-13637 - feat: display login on 401 responses

- README.md
- cmd/serve.go
- go.mod
- go.sum
- internal/config/specs.go
- internal/mail/html/user-invite.html
- internal/mail/interfaces.go
- internal/mail/service.go
- internal/mail/service_test.go
- internal/mail/templates.go
- internal/mail/templates_test.go
- pkg/identities/handlers.go
- pkg/identities/handlers_test.go
- pkg/identities/interfaces.go
- pkg/identities/service.go
- pkg/identities/service_test.go
- pkg/web/router.go
This PR introduces a new dependency for the low level email operations.
With this PR when a new identity is created through the REST API, an email is sent to the identity email with a link and code to use for the first login to complete the registration resetting the password.
Right now we're using a temporary template I made, but @huwshimi will implement a new one as soon as our UX expert provides one.
To perform a manual test for this PR you can deploy the Admin UI with its dependencies (you can disable authentication and authorization to make testing smoother) and with the MAIL_HOST, MAIL_PORT, MAIL_USERNAME, MAIL_PASSWORD env variables, and just create an identity.
Suggestion: use `maildev` for testing, run it as a docker container with
```
$ docker run -p 1080:1080 -p 1026:1025 …
```
> IAM 978 User invite - send email for identity creation with recovery code and link

- cmd/createIdentity.go
- deployments/kubectl/configMap.yaml
The pull request tries to add the CLI `create-identity` which aligns with what the corresponding HTTP API does.
> IAM-1054 add the create-identity CLI

- deployments/helm/mailhog/values.yaml
- deployments/kubectl/configMap.yaml
- skaffold.yaml
To resolve this [issue](https://github.com/canonical/identity-platform-admin-ui/issues/409).
> chore: update the skaffold deployment to include mail service

- internal/authorization/schema.openfga
This PR introduces a hierarchy for all `can_*` relations in the OpenFGA authorization model.
The hierarchy is as follows
- if a user can delete an object (top permission for can_* permission) then the user can also edit it
- if a user can edit an object, then the user can also view it
- if a user can view an object, the user doesn't inherit additional permissions from this relation only
So: `can_delete` >> `can_edit` >> `can_view`
Can create is not touched by this since it gets special treatment in the implementation.
This is done with the intention of simplifying both user experience and developer life when it comes to reasoning about user authorization based on entitlements.
This way we can rely on some simple implications to treat entitlements. Also, this allows us to not crowd the …
> feat: introduce hierarchy for can_relations

- cmd/createEmail.go
- cmd/createIdentity.go
This pull request tries to add a CLI command for the admins to compensate for email sending failure in the user invitation flow.
> feat: add the send invitation email cli command for admin to compensate user invitation email failure

- pkg/authentication/handlers_test.go
- pkg/authentication/oidc.go
- pkg/authentication/oidc_test.go
Remove the audience parameter from the oauth2 login redirection and adjusts tests accordingly.
This was manually tested also, and the jwt minted by hydra are still the same as expected.
Fixes #415
> IAM 1064 Don't request audience in login request

- pkg/ui/handlers.go
- ui/index.html
- ui/src/util/basePaths.spec.ts
- ui/src/util/basePaths.ts
Switch to html/template for rendering context path dynamically for `index.html`
This way when serving Admin UI under a context path we don't break the UI.
UI still expects to be under `/context-path(if present)/ui`.
We still need web team intervention to make the produced `index.html` to have the following prefix for its assets: `{{ . }}ui`
Example
```html
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Identity platform</title>
<link rel="shortcut icon" href="https://assets.ubuntu.com/v1/49a1a858-favicon-32x32.png" type="image/x-icon" />
<script>const global = globalThis;</script>
<script type="module" crossorigin src="{{ . }}ui/assets/index-D2_UOyoG.js"></script>
<link rel="stylesheet" crossorigin href="{{ . …
```
> IAM-951 fix broken href for non-empty context-path

- ui/index.html
- ui/src/util/basePaths.spec.ts
- ui/src/util/basePaths.ts
Fetch the basename for the router from the `<base>` tag. React Router doesn't support the base tag by default so we have to manually get the path.
https://warthogs.atlassian.net/browse/IAM-1137
Fixes: #431.
> IAM-1137 - refactor: fetch basename from base tag

- internal/authorization/util.go
- pkg/groups/handlers.go
- pkg/groups/handlers_test.go
- pkg/groups/interfaces.go
- pkg/groups/service.go
- pkg/groups/service_test.go
This PR adds implementation to check if the Assign{Identities,Roles} operation can be performed.
It leverages a BatchCheck that was previously not exposed on the underling client interface of the OpenFGA service.
- removed tracing from `buildGroupMember`-like functions
- moved existing OpenFGA tuple building functions under `internal/authorization/util.go` and introduced functions to build tuple elements for all types in the OpenFGA authorization model
- added CanAssignIdentities and CanAssignRoles methods in groups service
- added tests and adjusted existing after adoption of new functions
> IAM-1013 Implement granular payload authorization check for Group `Assign{Roles,Identities}` handlers

- pkg/ui/handlers.go
This PR provides a small change in how the context path is passed to the template that renders the index.html, making it work without escaping slashes that may be present in the context path itself.
This aims at fixing a possible cause of weird behavior in the loading of the UI.
> fix: avoid escaping when passing URL to template

- .github/workflows/publish.yaml
- Makefile
- cmd/Makefile
GO111MODULE param shouldn't be in use.
A couple of sources:
https://go.dev/blog/go116-module-changes#modules-on-by-default
https://maelvls.dev/go111module-everywhere/
> chore: GO111MODULE removed

- pkg/idp/third_party.go
- pkg/idp/validation.go
- pkg/idp/validation_test.go
- ui/src/pages/providers/ProviderCreate.tsx
The only way to address https://github.com/canonical/identity-platform-admin-ui/issues/405 right now is to remove the default value.
I opened issue https://github.com/canonical/identity-platform-admin-ui/issues/455 to address the lack of a dropdown and more info about how to populate the Mapper field in the Create Provider form.
- Since Kratos supports OIDC discovery, for the `generic` provider type we are allowing AuthURL and TokenURL to be empty in case IssuerURL is non empty
- Also, now IssuerURL can be empty if AuthURL and TokenURL are both provided
- Mapper is also allowed to be empty since Kratos will use the default schema in case that field is empty
- added a custom validation function to validate AuthURL and TokenURL presence in case IssuerURL is not specified
- added test entry …
> IAM-1047 provider defaults to non existant schema

- .github/workflows/ui-coverage.yml
- .github/workflows/ui.yaml
- ui/.gitignore
- ui/package.json
- ui/vitest.config.ts
- ui/yarn.lock
- Add test coverage reporter to GitHub Actions workflow files.
- Run UI CI only when UI files have changed.
There isn't a way to test this until it lands on main, but is largely copied over from rebac-admin.
https://warthogs.atlassian.net/browse/WD-17076
> WD-17076 - chore(ci): add UI test coverage reporter

- ui/src/components/IconLeft.tsx
- ui/src/components/IconRight.tsx
- ui/src/components/Pagination/Pagination.tsx
- Replace left and right icon components with standard icons.
https://warthogs.atlassian.net/browse/WD-17046
Before:
After:
> WD-17046 - refactor: replace icon components with standard icons

- .github/workflows/ui-coverage.yml
- .github/workflows/ui.yaml
- ui/README.md
- Fix the coverage path that gets uploaded.
- Download the coverage path to the correct location.
Note: this won't succeed until the workflow file has landed on main.
> chore(ci): fix UI coverage

- .github/workflows/ui-coverage.yml
Include the dir name in the output path of the coverage artefact. I've tested this: https://github.com/canonical/identity-platform-admin-ui/pull/481 so hopefully this will finally function correctly.
> chore(ci): fix ui coverage path

- ui/package.json
- ui/src/components/Pagination/Pagination.test.tsx
- ui/src/components/Pagination/Pagination.tsx
- ui/src/components/Pagination/types.ts
- ui/src/test/mocks/responses.ts
- ui/src/util/usePagination.test.ts
- ui/src/util/usePagination.ts
- ui/yarn.lock
- Added tests for the `Pagination` component and `usePagination` hook.
https://warthogs.atlassian.net/browse/WD-17052
> WD-17052 - chore(test): add pagination tests

- cmd/serve.go
- internal/config/specs.go
- internal/logging/logger.go
- internal/logging/logger_test.go
[IAM-1229](https://warthogs.atlassian.net/browse/IAM-1229)
Do not write logs to disk, the charm will need to migrate to LogForwarder
[IAM-1229]: https://warthogs.atlassian.net/browse/IAM-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Drop LOG_FILE support

- renovate.json
Based on @shipperizer suggestion https://github.com/canonical/identity-platform-admin-ui/pull/513#pullrequestreview-2557214603, we want to prevent OpenFGA sdk to go over the version that supports ListUsers API without introducing breaking changes, which is `v0.3.7`.
> Prevent renovate from upgrading openfga sdk

- renovate.json
This PR lowers the frequency for Renovate update runs. This is needed because since last year Renovate runs fell into a "void" due to many 422 Unprocessable Enitity errors returned by the Github API to the client used by Renovate.
More info in the issue I opened on the renovate repo https://github.com/renovatebot/renovate/discussions/33761.
- removed "schedule" config for specific packageRules since they were all equal to the defaul "at any time"
- added timezone config to make sure the cron schedule provides expected results
**NB**: changes to the schedule will most likely come as we reassess the situation in the near future.
> Lower update frequency to avoid spamming

- .github/workflows/build.yaml
- .github/workflows/ossf.yaml
- .github/workflows/unittest.yaml
Upload artifact action v3 got deprecated.
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Upgrade upload-artifact to v4 after deprecation

- .github/workflows/publish.yaml
Download artifact action v3 got deprecated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Upgrade download-artifact to v4

- internal/openfga/client.go
- internal/openfga/interfaces.go
- internal/openfga/noop.go
- pkg/groups/handlers.go
- pkg/groups/handlers_test.go
- pkg/groups/interfaces.go
- pkg/groups/service.go
- pkg/groups/service_test.go
- pkg/roles/handlers.go
- pkg/roles/handlers_test.go
- pkg/roles/interfaces.go
- pkg/roles/service.go
- pkg/roles/service_test.go
- pkg/web/interfaces.go
This PR build on the preparatory work of the previous OpenFGA upgrades from the PRs mentioned below.
Adoption of the ListUsers API in both the `roles` package and the `groups` package to improve the implementation of the 
- `roles.ListRoleGroups`
- `groups.ListGroupIdentities`
The `OpenFGACoreClientInterface` for the core OpenFGA client has been updated with the additional methods for the ListUsers API.
The `ListUsers` replaces the `ReadTuples`. One difference to note is that the ListUsers doesn't provide paginated results so the continuation token has been removed from the signature and the return type.
Tests have been adjusted accordingly.
- https://github.com/canonical/identity-platform-admin-ui/pull/513
- https://github.com/canonical/identity-platform-login-ui/pull/427
- …
> IAM-1285 Adopt ListUsers API

- ui/src/pages/providers/ProviderCreate/ProviderCreate.test.tsx
- ui/src/pages/providers/ProviderCreate/ProviderCreate.tsx
- ui/src/pages/providers/ProviderEdit/ProviderEdit.test.tsx
- ui/src/pages/providers/ProviderEdit/ProviderEdit.tsx
- ui/src/pages/providers/ProviderForm/ProviderForm.tsx
Pass the name to the label value when created/editing idps.
Also fixed an issue when updating idps where it would pass an empty string to `requested_claims` which is not valid JSON.
https://warthogs.atlassian.net/browse/IAM-1057
Fixes: #410.
> feat: pass label when creating idps

- go.mod
- go.sum
- internal/http/types/gRPC_mappers.go
- internal/http/types/gRPC_mappers_test.go
- internal/http/types/generic.go
- internal/http/types/token.go
- pkg/roles/gRPC_handlers.go
- pkg/roles/gRPC_handlers_test.go
- pkg/roles/handlers.go
- pkg/roles/handlers_test.go
- pkg/web/router.go
This PR introduces the first API (Roles) based on the gRPC-gateway implementation from the generated code in https://github.com/canonical/identity-platform-api.
The gRPC_mapper.go file contains two functions needed to make sure the new APIs match the existing one.
- `SetHeaderFromMetadataFilter` is needed to make sure that response headers are set on the response object
- `ForwardErrorResponseRewriter` is needed to make sure error responses match the ones from the rest of the APIs
The gRPC_handlers.go contains the gRPC handlers implementations, mimicing what has been done for the handlers.go.
Test have been added for every new piece of code.
- `Response` object has been enriched with `omitempty` to avoid serializing nil values
- fixed a typo in the word "Rule" which is supposed to be …
> IAM-1311 Migrate roles api to gRPC-gateway based server

- go.mod
- go.sum
- pkg/status/gRPC_handlers.go
- pkg/status/gRPC_handlers_test.go
- pkg/web/router.go
Port Status API to protobuf based/gRPC gateway based implementation.
Builds on top of https://github.com/canonical/identity-platform-api/pull/16
> IAM-1319 Migrate Status API

- pkg/metrics/handlers.go
- pkg/web/router.go
This PR doesn't really migrate metrics API. What it does is
- exposing an `http.Handler` for ease of registration, which wraps the current metrics handler
- this allows us to have a final version of the ported APIs that will allow us to tidy up the registration for all API without having broken down pieces added to the mux as we're doing right now with the new mux for the gRPC gateway
> IAM-1320 "Migrate" metrics api

- go.mod
- go.sum
- pkg/groups/gRPC_handlers.go
- pkg/identities/gRPC_handlers.go
- pkg/identities/gRPC_handlers_test.go
- pkg/identities/gRPC_mappers.go
- pkg/identities/gRPC_mappers_test.go
- pkg/web/router.go
This PR add support for the Identities API (gRPC-gateway based).
A GrpcMapper struct has been added to brdige the mapping from and to the models used by admin uI, which are in turn taken from the Kratos SDK. This doesn't allow us to edit the json tags as I would have wanted to, that is why in the gRPC_mapper_test.go file you see I had to "normalize" some result since semantis is correctly preserved in the regular processing of the data by the actual service.
The gRPC mapper tests only focus on the happy path. This is due to difficulty in finding a way to generate and test an error that makes sense + the amount of time this task already took.
gRPC_handlers_test file to cover for the five endpoints of the v0 Identities API.
> IAM-1315 Port identities api

- go.mod
- go.sum
- pkg/storage/storage.go
This PR builds on top of https://github.com/canonical/identity-platform-admin-ui/pull/574.
It leverages https://github.com/exaring/otelpgx.
The addition is for tracing db connections and also collect db stats. This happens only if tracing is enabled (I did this to avoid having a different bool to control this behavior).
A small changes was required on the pgx driver db connection in order to properly configure the tracer.
This changes nothing in the end product since we still rely on the standard `database/sql` interface which was already a pool implementation.
This closes https://github.com/canonical/identity-platform-admin-ui/issues/572
> IAM-1547 Add database tracer

- cmd/serve.go
- go.sum
- pkg/ui/handlers.go
- pkg/web/router.go
This PR refactors the NewRouter function to use the functional options pattern, allowing for cleaner and more flexible configuration. The following changes were made:
- adopted functional options pattern in NewRouter for better extensibility and readability
- simplified logic in NewRouter, reducing repetition and unnecessary
- Removed infrequently used variables that were only declared and used once, inlined their usage instead
- Removed the ui.Config struct for its simplicity, but we should add it back as soon as the UI handler needs more info
If we like this, we could easily apply the same pattern to our API handlers and services.
The "missing" part to make this actually 100% effective is to have sensible defaults for every settings in the available options, which right now we don't …
> IAM-1276 Improve NewRouter function and streamline code

- Makefile
This PR updates the makefile to make sure that the outputs for goose commands are repeatable by matching the names of the .PHONY's.
> fix: update Makefile .PHONYs

- Makefile
- deployments/helm/postgresql/values.yaml
- deployments/kubectl/configMap.yaml
- structure-tests.yaml
While trying to get the platform running, I've come across a number of issues which I've fixed:
- Add missing DSN env var
- Create `admin-service` database along with other databases
- Use `iam:iam` as postgres credentials for goose migrations
- `idps` -> `providers` for `IDPCONFIG_NAME`
- JSON typo in default IDP configuration
> fix: various startup bugs
